"""adding unique constraints for reddit_sentiments

Revision ID: 187da7e2bdf9
Revises: b54e143ea0d0
Create Date: 2025-08-03 23:46:44.504294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187da7e2bdf9'
down_revision: Union[str, Sequence[str], None] = 'b54e143ea0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_post_comment', 'reddit_sentiments', ['post_id', 'comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_comment', 'reddit_sentiments', type_='unique')
    # ### end Alembic commands ###
