"""add post_id as an indexed field

Revision ID: 239c38f6cc5a
Revises: e5d15e0f63e5
Create Date: 2025-07-09 20:40:37.750585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '239c38f6cc5a'
down_revision: Union[str, Sequence[str], None] = 'e5d15e0f63e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reddit_comments_post_id'), 'reddit_comments', ['post_id'], unique=False)
    op.drop_constraint(op.f('reddit_posts_post_id_key'), 'reddit_posts', type_='unique')
    op.create_index(op.f('ix_reddit_posts_post_id'), 'reddit_posts', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_posts_post_id'), table_name='reddit_posts')
    op.create_unique_constraint(op.f('reddit_posts_post_id_key'), 'reddit_posts', ['post_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_reddit_comments_post_id'), table_name='reddit_comments')
    # ### end Alembic commands ###
