"""add ml_models, orders, and wallets

Revision ID: 2d6a77233c2d
Revises: 187da7e2bdf9
Create Date: 2025-08-11 21:19:57.448537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d6a77233c2d'
down_revision: Union[str, Sequence[str], None] = '187da7e2bdf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('prediction_currency', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('numeric_features', sa.JSON(), nullable=True),
    sa.Column('categorical_features', sa.JSON(), nullable=True),
    sa.Column('target_variable', sa.String(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=False),
    sa.Column('updated_utc', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_model'), 'ml_models', ['model'], unique=False)
    op.create_index(op.f('ix_ml_models_name'), 'ml_models', ['name'], unique=True)
    op.create_index(op.f('ix_ml_models_prediction_currency'), 'ml_models', ['prediction_currency'], unique=False)
    op.create_index(op.f('ix_ml_models_provider'), 'ml_models', ['provider'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('order_currency', sa.String(), nullable=False),
    sa.Column('ordered_price', sa.Float(), nullable=False),
    sa.Column('ordered_quantity', sa.Float(), nullable=False),
    sa.Column('projected_price', sa.Float(), nullable=False),
    sa.Column('ordered_at', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.Integer(), nullable=True),
    sa.Column('sold_price', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_currency'), 'orders', ['currency'], unique=False)
    op.create_index(op.f('ix_orders_order_currency'), 'orders', ['order_currency'], unique=False)
    op.create_index(op.f('ix_orders_platform'), 'orders', ['platform'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('tag_or_memo', sa.String(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('balance_currency', sa.String(), nullable=False),
    sa.Column('balance_utilization', sa.Float(), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=False),
    sa.Column('updated_utc', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_address'), 'wallets', ['address'], unique=True)
    op.create_index(op.f('ix_wallets_currency'), 'wallets', ['currency'], unique=False)
    op.create_index(op.f('ix_wallets_name'), 'wallets', ['name'], unique=True)
    op.create_index(op.f('ix_wallets_platform'), 'wallets', ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_platform'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_name'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_currency'), table_name='wallets')
    op.drop_index(op.f('ix_wallets_address'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_platform'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_currency'), table_name='orders')
    op.drop_index(op.f('ix_orders_currency'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_ml_models_provider'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_prediction_currency'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_name'), table_name='ml_models')
    op.drop_index(op.f('ix_ml_models_model'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
