"""updated post_id migration

Revision ID: 5446b7910028
Revises: f2dfe098fc47
Create Date: 2025-07-07 21:34:53.351197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5446b7910028'
down_revision: Union[str, Sequence[str], None] = 'f2dfe098fc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reddit_comments', 'post_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('reddit_posts', sa.Column('post_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'reddit_posts', ['post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reddit_posts', type_='unique')
    op.drop_column('reddit_posts', 'post_id')
    op.alter_column('reddit_comments', 'post_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
