"""add name to currency_prices table

Revision ID: 71283fe3a516
Revises: 2dd1f1e6a841
Create Date: 2025-07-11 13:31:24.061523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71283fe3a516'
down_revision: Union[str, Sequence[str], None] = '2dd1f1e6a841'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency_prices', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency_prices', 'name')
    # ### end Alembic commands ###
