"""add llm_providers model

Revision ID: b54e143ea0d0
Revises: f282d0b65cf8
Create Date: 2025-08-01 13:28:04.854031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54e143ea0d0'
down_revision: Union[str, Sequence[str], None] = 'f282d0b65cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('default_api_key', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('tokens_per_minute', sa.Integer(), nullable=True),
    sa.Column('calls_per_minute', sa.Integer(), nullable=True),
    sa.Column('total_used_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('access_token_expiry', sa.Integer(), nullable=True),
    sa.Column('access_token_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_providers_model'), 'llm_providers', ['model'], unique=False)
    op.create_index(op.f('ix_llm_providers_name'), 'llm_providers', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_providers_name'), table_name='llm_providers')
    op.drop_index(op.f('ix_llm_providers_model'), table_name='llm_providers')
    op.drop_table('llm_providers')
    # ### end Alembic commands ###
