"""updated comment_id migration for reddit_comments

Revision ID: e5d15e0f63e5
Revises: 5446b7910028
Create Date: 2025-07-07 22:07:53.680581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d15e0f63e5'
down_revision: Union[str, Sequence[str], None] = '5446b7910028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_comments', sa.Column('comment_id', sa.String(), nullable=True))
    op.alter_column('reddit_comments', 'parent_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reddit_comments', 'parent_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('reddit_comments', 'comment_id')
    # ### end Alembic commands ###
