"""add reddit_sentiments model

Revision ID: f282d0b65cf8
Revises: 71283fe3a516
Create Date: 2025-08-01 11:38:53.449115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f282d0b65cf8'
down_revision: Union[str, Sequence[str], None] = '71283fe3a516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reddit_sentiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('crypto_sentiment', sa.String(), nullable=False),
    sa.Column('future_sentiment', sa.String(), nullable=False),
    sa.Column('emotion', sa.String(), nullable=False),
    sa.Column('subjective', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reddit_sentiments_post_id'), 'reddit_sentiments', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reddit_sentiments_post_id'), table_name='reddit_sentiments')
    op.drop_table('reddit_sentiments')
    # ### end Alembic commands ###
